'use client';

import { useState } from 'react';

const languages = ['JavaScript', 'TypeScript', 'Python', 'Go', 'Rust', 'Java', 'C++', 'SQL', 'Bash'];
const examples = [
  { title: 'REST API endpoint', lang: 'TypeScript', prompt: 'Create a REST API endpoint for user authentication with JWT tokens' },
  { title: 'Binary search', lang: 'Python', prompt: 'Write a binary search algorithm with O(log n) complexity' },
  { title: 'React hook', lang: 'TypeScript', prompt: 'Create a custom React hook for fetching data with loading and error states' },
  { title: 'SQL query', lang: 'SQL', prompt: 'Write a SQL query to find the top 10 customers by total order value' },
];

const demoCode: Record<string, string> = {
  TypeScript: `// Generated by Gbot AI ✨
import jwt from 'jsonwebtoken';
import { Request, Response } from 'express';

interface AuthPayload {
  userId: string;
  email: string;
}

export async function loginHandler(req: Request, res: Response) {
  const { email, password } = req.body;
  
  // Validate credentials
  const user = await User.findOne({ email });
  if (!user || !await user.verifyPassword(password)) {
    return res.status(401).json({ error: 'Invalid credentials' });
  }
  
  // Generate JWT token
  const token = jwt.sign(
    { userId: user._id, email: user.email } as AuthPayload,
    process.env.JWT_SECRET!,
    { expiresIn: '7d' }
  );
  
  res.json({ token, user: { id: user._id, email: user.email } });
}`,
  Python: `# Generated by Gbot AI ✨
def binary_search(arr: list, target: int) -> int:
    """
    Binary search with O(log n) time complexity.
    Returns index of target, or -1 if not found.
    """
    left, right = 0, len(arr) - 1
    
    while left <= right:
        mid = (left + right) // 2
        
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1
    
    return -1  # Target not found

# Example usage
nums = [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
print(binary_search(nums, 7))   # Output: 3
print(binary_search(nums, 6))   # Output: -1`,
};

export default function CodePage() {
  const [prompt, setPrompt] = useState('');
  const [lang, setLang] = useState('TypeScript');
  const [loading, setLoading] = useState(false);
  const [code, setCode] = useState('');
  const [copied, setCopied] = useState(false);

  const generate = async (customPrompt?: string) => {
    const p = customPrompt || prompt;
    if (!p.trim() || loading) return;
    setPrompt(p);
    setLoading(true);
    setCode('');
    await new Promise(r => setTimeout(r, 1500));
    setCode(demoCode[lang] || demoCode['TypeScript']);
    setLoading(false);
  };

  const copy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="animate-fade-in" style={{ maxWidth: 900, margin: '0 auto' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 32 }}>
        <div style={{ width: 44, height: 44, background: 'rgba(6,182,212,0.15)', borderRadius: 14, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.3rem' }}>💻</div>
        <div>
          <h1 style={{ fontSize: '1.4rem', fontWeight: 800 }}>Code Generation</h1>
          <p style={{ color: '#6b7280', fontSize: '0.82rem' }}>Generate clean code in any language</p>
        </div>
      </div>

      {/* Input */}
      <div style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: 20, padding: 28, marginBottom: 24 }}>
        <div style={{ display: 'flex', gap: 12, marginBottom: 16, flexWrap: 'wrap' }}>
          <div style={{ flex: 1, minWidth: 200 }}>
            <label style={{ color: '#9ca3af', fontSize: '0.8rem', display: 'block', marginBottom: 8 }}>Language</label>
            <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
              {languages.map(l => (
                <button key={l} onClick={() => setLang(l)} style={{
                  padding: '6px 14px', borderRadius: 8, border: `1px solid ${lang === l ? '#06b6d4' : 'rgba(255,255,255,0.1)'}`,
                  background: lang === l ? 'rgba(6,182,212,0.12)' : 'transparent',
                  color: lang === l ? '#67e8f9' : '#6b7280', cursor: 'pointer', fontSize: '0.8rem', fontWeight: 500
                }}>{l}</button>
              ))}
            </div>
          </div>
        </div>

        <textarea className="chat-input" rows={3} value={prompt}
          onChange={e => setPrompt(e.target.value)}
          onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); generate(); }}}
          placeholder="Describe what you want to build... e.g. 'Create a function to validate email addresses'"
          style={{ marginBottom: 16 }}
        />

        <button className="btn-primary" onClick={() => generate()} disabled={!prompt.trim() || loading}
          style={{ width: '100%', padding: '14px', fontSize: '1rem', background: 'linear-gradient(135deg,#0891b2,#06b6d4)' }}>
          {loading ? '⚡ Generating...' : '⚡ Generate Code'}
        </button>
      </div>

      {/* Output */}
      {(loading || code) && (
        <div style={{ background: '#0d1117', border: '1px solid rgba(255,255,255,0.08)', borderRadius: 20, overflow: 'hidden' }}>
          <div style={{ padding: '12px 20px', borderBottom: '1px solid rgba(255,255,255,0.06)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
              <div style={{ width: 12, height: 12, borderRadius: '50%', background: '#ef4444' }} />
              <div style={{ width: 12, height: 12, borderRadius: '50%', background: '#f59e0b' }} />
              <div style={{ width: 12, height: 12, borderRadius: '50%', background: '#22c55e' }} />
              <span style={{ color: '#6b7280', fontSize: '0.8rem', marginLeft: 8 }}>Generated {lang}</span>
            </div>
            {code && (
              <button onClick={copy} style={{
                background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)',
                borderRadius: 8, padding: '6px 14px', color: copied ? '#4ade80' : '#9ca3af',
                cursor: 'pointer', fontSize: '0.8rem'
              }}>
                {copied ? '✓ Copied!' : '📋 Copy'}
              </button>
            )}
          </div>
          <pre style={{ padding: 24, overflowX: 'auto', fontSize: '0.85rem', lineHeight: 1.8, color: loading ? '#374151' : '#e2e8f0', minHeight: 200 }}>
            {loading ? '// Generating your code...\n// Please wait...' : code}
          </pre>
        </div>
      )}

      {/* Examples */}
      {!code && !loading && (
        <div>
          <p style={{ color: '#6b7280', fontSize: '0.85rem', marginBottom: 16 }}>Quick examples:</p>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))', gap: 12 }}>
            {examples.map(ex => (
              <button key={ex.title} onClick={() => { setLang(ex.lang); generate(ex.prompt); }}
                style={{
                  background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.08)',
                  borderRadius: 14, padding: '16px 20px', color: '#e5e7eb', cursor: 'pointer', textAlign: 'left', transition: 'all 0.2s'
                }}>
                <p style={{ fontWeight: 600, marginBottom: 4, fontSize: '0.875rem' }}>{ex.title}</p>
                <p style={{ color: '#6b7280', fontSize: '0.78rem', lineHeight: 1.4 }}>{ex.prompt}</p>
                <span style={{ color: '#06b6d4', fontSize: '0.75rem', marginTop: 8, display: 'block' }}>{ex.lang}</span>
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
